global:
  scrape_interval: 15s
scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs: [{targets: ["api:8000"]}]
  - job_name: producer
    static_configs: [{targets: ["producer:9101"]}]
  - job_name: consumer
    static_configs: [{targets: ["consumer:9102"]}]
